package defaultPackage;

import java.util.Map;
import java.util.HashMap;
import org.jbpm.casemgmt.api.CaseService;
import org.jbpm.casemgmt.api.model.instance.CaseFileInstance;
import org.jbpm.document.Document;
import org.jbpm.services.api.service.ServiceRegistry;

rule "Invalid document name - reupload"
when 
    $caseData : CaseFileInstance()
    Document(name == "invalid.pdf") from $caseData.getData("hwSpec")
          
then 
    
    System.out.println("Hardware specification is invalid");
    $caseData.remove("hwSpec");
    update($caseData);
    CaseService caseService = (CaseService) ServiceRegistry.get().service(ServiceRegistry.CASE_SERVICE);
    caseService.triggerAdHocFragment($caseData.getCaseId(), "Prepare hardware spec", null);
end

rule "Mark as ordered"
when 
    $caseData : CaseFileInstance(data.get("orderNumber") != null, data.get("ordered") == null)
          
then 
    
    System.out.println("Order has been placed with number " + $caseData.getData("orderNumber"));
    $caseData.add("ordered", true);
    update($caseData);
end