package org.jbpm.demo.itorders;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Order implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Order() {
    }




}